---
- name: check for available updates (Red Hat)
  hosts: all
  become: yes
  tasks:
    - name: check for available updates (Red Hat-based)
      yum:
        name: '*'
        state: latest
        update_cache: yes
      register: update_result

    - name: show the list of packages to be updated
      debug:
        var: update_result.results
